backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "book"
    label: "Book"
    folder: "src/pages/book"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "book-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {
          label: "Cover Image", 
          name: "coverImage", 
          widget: "object", 
          fields: 
          [
            {label: Image, name: image, widget: image}, 
            {label: Alt, name: alt, widget: string}
            ]
            }
      - {label: "Description", name: "description", widget: "text"}
      - {
          label: "Reviews", 
          name: "reviews", 
          widget: list,
          fields: [
            {label: "Reviewer Name", name: "reviewerName", widget: "string"},
            {label: "Message", name: "message", widget: "string"}
          ]
          }
      - {label: "Body", name: "body", widget: "markdown"}
      - { 
          label: "Links To Buy", 
          name: "linksToBuy", 
          widget: "list",
          fields: [
            {label: "Label", name: "label", widget: "string"},
            {
                label: "Link Image", 
                name: "linkImage", 
                widget: "object", 
                fields: 
                [
                  {label: Image, name: image, widget: image}, 
                  {label: Alt, name: alt, widget: string}
                  ]
              },
              {label: "LinkURL", name: "linkURL", widget: "string"}
            ]
          }

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "Index Page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page" }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Main Image",
              name: "mainImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" }
                ]
            }
          - { label: "Body", name: "body", widget: "markdown" }
          - {
              label: "Awards",
              name: "awards",
              widget: "list",
              fields:
                [
                  { label: "Award Title", name: "awardTitle", widget: "string" },
                  {
                    label: "Award Image",
                    name: "awardImage",
                    widget: "object",
                    fields:
                      [
                        { label: "Name", name: "name", widget: "string" },
                        { label: "Image", name: "image", widget: "image" },
                        { label: "Image Description", name: "imageAlt", widget: "string" }
                      ]
                  }
                ]
            }
      - file: "src/pages/media/index.md"
        label: "Media"
        name: "media"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "media-page" }
          - { 
              label: "Youtube Videos", 
              name: "youtubeVideos", 
              widget: "list",
              fields: [
                {label: "Title", name: "title", widget: "string", optional: true},
                {label: "Description", name: "description", widget: "string", optional: true},
                {label: "Youtube URL", name: "url", widget: "string"}
                ]
            }
      - file: "src/pages/publication/index.md"
        label: "Publication"
        name: "publication"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "publication-page" }
          - { 
              label: "All Publications",
              name: "publicationList",
              widget: "list",
              fields: [
                {label: "Title", name: "title", widget: "string"},
                {
                  label: "Publication Image", 
                  name: "publicationImage", 
                  widget: "object",
                  fields: [
                    {label: "Image", name: "image", widget: "image"},
                    {label: "Description", name: "imageAlt", widget: "string"}
                  ]
                  }
              ]
              }   
          


